### ISSUE TITLE
Docker / rules_oci example?

### ISSUE THREAD

**Issue by njlr** [jvolkman/rules_pycross#111]
Hello :wave:

I was wondering if there is an example of bundling a Python app, built with Bazel, into a Docker image?

I think this is a good application of `rules_pycross` since if you are building a Linux AMD64 Docker image (a common deployment target) on macOS ARM (a common developer setup), then you are doing a cross-compile. 

The standard `rules_python` assumes that the host is the target, so I was unable to get that working with a hermetic interpreter, native packages etc. 

Has anyone accomplished this with `rules_pycross`?
Is there an example to look at?

**Comment by jvolkman** [comment]
The only thing I know of is https://github.com/stackb/pycross_image, but I haven't tried it myself.

**Comment by njlr** [comment]
I was able to string things together: https://github.com/njlr/rules_pycross_oci

**Comment by blockjon-dd** [comment]
@njlr can you please share your solution?

**Comment by njlr** [comment]
> @njlr can you please share your solution?

It's linked above
