### ISSUE TITLE
Wheel build for lxml fails 

### ISSUE THREAD

**Issue by codebreach** [jvolkman/rules_pycross#33]
More of a question (i guess)

So I am able to get dependencies with lxml build for linux target but not for mac aarm64 target. (on a Mac M1)

The `lxml` pip package does not publish a `aarm64` wheel so it correctly tries to build it... but when building it says that the `libxml2` development page is not installed.

How am I to pass the information of the local libxml2 package? 

```
ERROR: /Users/madhav/Code/sdroot/mr-ping/utils/pypi/BUILD:5:8: Building lxml-4.9.2.tar.gz failed: (Exit 1): wheel_builder failed: error executing command bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder --sdist external/lock_sdist_lxml_4.9.2/file/lxml-4.9.2.tar.gz --sysconfig-vars ... (remaining 15 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
I0312 21:47:10.886236 8611248768 __init__.py:439] Building wheel...
===== BUILD FAILED =====
Building lxml version 4.9.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.

```

libxml2 is present and works when lxml is built from source

```
~/Code/lxml-4.9.2 % python3 setup.py bdist_wheel
Building lxml version 4.9.2.
Building without Cython.
Building against libxml2 2.9.4 and libxslt 1.1.29
[...truncated...]
```

**Comment by jvolkman** [comment]
I haven't tried building that package so I can't offer specific advice. First step would be to determine how the package is attempting to locate libxml2. Unfortunately python package builds can do basically whatever they want.

I'm working on a branch that should offer better tools for handling package builds. You can see some examples [here](https://github.com/jvolkman/rules_pycross/tree/dev/external/examples/external_linking/deps).

**Comment by codebreach** [comment]
very cool. seems like this should fix it

The code that detects these versions is in https://github.com/lxml/lxml/blob/3d4e60f2835e4d85fd357c182656d3eca534f2ff/setupinfo.py#L398-L439

which essentially checks a few different environment variables. 

based on your examples and my understanding doing something similar to numpy/postgres should work. 

I am going to try to replicate with the same flow as postgres. will share findings.

**Comment by jvolkman** [comment]
The stuff in that example is now in the latest release.
