### ISSUE TITLE
This project is incompatible with the pdm 2.8 lock format

### ISSUE THREAD

**Issue by aignas** [jvolkman/rules_pycross#39]
Before loading the `pdm.lock` file it would be great to first check that the lock version is compatible with what `rules_pycross` supports. `pdm 2.8` which was released last week drastically changes the format and the rules_pycross is now failing with slightly difficult to understand errors.

**Comment by jvolkman** [comment]
@betaboon have you run into this yet?

**Comment by betaboon** [comment]
we haven't updated to pdm 2.8 yet.

the suggestion with checking the `lock_version` (which is contained in the lockfile) is very good.

I'll try to take a look in the coming days. I'm quite busy atm, thus i cannot give any time guarantees tho.

i will report back.

**Comment by betaboon** [comment]
i just took a quick look:
1. the lockfile format has changed a lot and doesn't contain the package-urls by default anymore. the inclusion of the package-urls can be enforced with `--static-urls` now tho.
2. some pdm-internals that i was using have changed/gone missing. so i will have to investigate if there is a different approach that i can take to bring back the functionality.

**Comment by jvolkman** [comment]
Thanks for looking! I suppose for now we can add a version check and output a more helpful error message.

**Comment by betaboon** [comment]
the PR #40 should fix this. @aignas can you give it a try ?

fyi: 
when creating the lockfile you need to run `pdm lock --static-urls` to contain the urls in the lockfile.
this gets saved in the lockfile and will not be required afterwards.

**Comment by betaboon** [comment]
@aignas did you get a chance to check if the PR resolves the issue for you ?
