### ISSUE TITLE
First-party wheel support?

### ISSUE THREAD

**Issue by pcj** [jvolkman/rules_pycross#83]
I opened a PR https://github.com/bazelbuild/rules_python/pull/1776 that helps for building / publishing wheels that contain first party code (1p; for example, monorepo contains source py libraries, want to publish them to artifactory for non-monorepo consumers) using their `py_wheel` and `py_project` rules.

Should I be using rules_pycross for this?  So far rules_pycross has been great for getting 3p deps from pypi, but I'm wondering if rules_pycross is a good fit for the use case above.

**Comment by jvolkman** [comment]
Pycross doesn't really know how to build wheels, so I don't think so. In [PEP 517](https://peps.python.org/pep-0517/) terminology, Pycross is a build frontend, and it invokes the backend via the 517 interface. It's that backend's job to actually construct a wheel.

Some day I'd like to make a Bazel-based build backend which would likely utilize the wheel rules in rules_python.

That said, regarding your other PR, if `PyRequirementInfo` lands upstream maybe it makes sense to have `pycross_wheel_library` return it.

**Comment by pcj** [comment]
Thanks for the response, I'll go ahead and close this issue.
