### ISSUE TITLE
Patch wheel support?

### ISSUE THREAD

**Issue by chestnutprog** [jvolkman/rules_pycross#84]
I want to patch a prebuilt wheel. Can we have something like `whl_patches` in rules_python?

**Comment by betaboon** [comment]
this should be resolved by #96

**Comment by keith** [comment]
@betaboon @jvolkman the original request here actually isn't resolved by this change, can we reopen this one? Is the potential solution to add patches to package_annotation and wire that through?

**Comment by chestnutprog** [comment]
I can draft a PR on this. BTW, I don't have permission to reopen it, Is there something wrong with permission configs? @jvolkman 

<img width="963" height="110" alt="Image" src="https://github.com/user-attachments/assets/fe55ec47-c7df-4724-977d-84ccbcbc2ffe" />
